# .goreleaser.yml
# Build customization
builds:
  - binary: awsclihelper
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
release:
  prerelease: auto
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Update README
      - Update CHANGELOG
furies:
  - 
    account: jjkirkpatrick
    secret_name: "{{ .Env.FURYIO_TOKEN }}"

    # IDs to filter by.
    # Defaults to empty, which means all packages created by all nfpm configurations get uploaded.
    ids:
      - packages

    # Formats to upload.
    # Available options are `deb` and `rpm`.
    # Defaults to `deb` and `rpm`.
    formats:
      - deb
      - rpm
